#-----------------------------------------------------------------------
# TITLE:
#   subtree.tcl
#
# AUTHOR:
#   Will Duquette
#
# DESCRIPTION:
#   Kite: app_kite(n), subtree manager.  A subtree is a collection of files
#   generated by Kite as a new subtree of a project.  subtrees are defined
#   by exported commands in the subtree ensemble.
#
#-----------------------------------------------------------------------

namespace eval subtree:: {
    namespace ensemble create
}


