#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# AUTHOR:
#    William H. Duquette
#
# DESCRIPTION:
#    pkgIndex file for package kiteinfo 
#
#    Generated by Kite at Fri Jun 20 13:09:32 PDT 2014

package ifneeded kiteinfo 1.0 [list source [file join $dir pkgModules.tcl]]




