#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena-kite
#
# DESCRIPTION:
#    kiteinfo(n) package modules file
#
#    Generated by Kite from kiteinfo_pkgModules.template.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

package provide kiteinfo 1.0

#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::kiteinfo:: {
    variable library [file dirname [info script]]
}

#-----------------------------------------------------------------------
# Modules

source [file join $::kiteinfo::library kiteinfo.tcl]
