#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# AUTHOR:
#    Will Duquette
#
# DESCRIPTION:
#    pkgModules file for package kiteinfo
#
#
#    Generated by Kite at Fri Jun 20 13:32:55 PDT 2014
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

package provide kiteinfo 1.0

#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::kiteinfo:: {
    variable library [file dirname [info script]]
}

#-----------------------------------------------------------------------
# Modules

source [file join $::kiteinfo::library kiteinfo.tcl]

