#-----------------------------------------------------------------------
# TITLE:
#   subtree.tcl
#
# AUTHOR:
#   Will Duquette
#
# DESCRIPTION:
#   Kite: kiteapp(n), subtree manager.  A subtree is a collection of files
#   generated by Kite as a new subtree of a project.  subtrees are defined
#   by exported commands in the ::kiteapp::subtree ensemble.
#
#-----------------------------------------------------------------------

namespace eval ::kiteapp::subtree:: {
    namespace ensemble create
}

